SCRIPT_DIR="$(dirname "$(readlink -f "$BASH_SOURCE")")"
PLUG_DIR="$SCRIPT_DIR/ext/blockchain-k-plugin"
PLUG_SRC_DIR="$PLUG_DIR/plugin-c"
PLUG_BUILD_DIR="$PLUG_DIR/build"
export PATH="$SCRIPT_DIR/ext/k/k-distribution/bin:$PATH"
export KOMPILE_OPTS="--backend llvm -ccopt $SCRIPT_DIR/time.cpp -ccopt $SCRIPT_DIR/tolowercase.cpp -ccopt $PLUG_SRC_DIR/blake2.cpp -ccopt $PLUG_SRC_DIR/hash.cpp -ccopt $PLUG_SRC_DIR/secp256k1.cpp -ccopt -std=c++14 --hook-namespaces TIME --hook-namespaces HASH --hook-namespaces SECP256K1 -ccopt -L$PLUG_BUILD_DIR/lib -ccopt -I$PLUG_BUILD_DIR/include -ccopt -lff -ccopt -lcryptopp -ccopt -lsecp256k1 -ccopt -lprocps --debug -I $SCRIPT_DIR/.build -I $SCRIPT_DIR/compat"
export LUA_PATH="$SCRIPT_DIR/ext/pandoc-tangle/?.lua;;"
export TANGLER="$SCRIPT_DIR/ext/pandoc-tangle/tangle.lua"
