$contract { code { DROP ; 
         PUSH int 5 ;
         PUSH int 25 ;
         PUSH int 125 ;
         DIP { ADD } ;
         DROP ;
         NIL operation ;
         PAIR }; 
storage unit;
parameter unit; } ; 
$paramtype unit ;
$storagetype unit ;
$balance 0 ;
$amount 0 ;
$now 0 ;
$myaddr 0 ;
$knownaddrs ;
$sourceaddr 0 ;
$senderaddr 0 ;
$param Unit ;
$storage Unit ;
