#!/usr/bin/env bash

cd "$(dirname $0)"

pandoc --to latex -o lb-report.pdf      \
       --pdf-engine=xelatex             \
       -V geometry:margin=2cm           \
       README.md lb-properties.md
