$contract { code { DROP ;
         EMPTY_SET int ;
         PUSH bool True ;
         PUSH int 5 ;
         UPDATE ;
         PUSH bool True ;
         PUSH int 5 ;
         UPDATE ;
         PUSH bool True ;
         PUSH int 20 ;
         UPDATE ;
         PUSH bool True ;
         PUSH int 0 ;
         UPDATE ;
         PUSH bool True ;
         PUSH int 23 ;
         UPDATE ;
         PUSH bool True ;
         PUSH int 13 ;
         UPDATE ;
         PUSH bool True ;
         PUSH int 13 ;
         UPDATE ;
         NIL operation ;
         PAIR  }; 
storage unit ;
parameter unit ; } ; 
$paramtype unit ;
$storagetype unit ;
$balance 0 ;
$amount 0 ;
$now 0 ;
$myaddr 0 ;
$knownaddrs ;
$sourceaddr 0 ;
$senderaddr 0 ;
$param Unit ;
$storage Unit ;
